---
- hosts: localhost
	connection: local
	gather_facts: true		# gather OS info that is made available for tasks/roles
	become: yes						#
	vars:
		logs:
			- file: /var/log/messages
				group_name: "system_logs"
	roles:
		- common
